linters-settings:
  lll:
    line-length: 170
  goconst:
    ignore-tests: true
  revive:
    rules:
      - name: dot-imports
        disabled: true
linters:
  enable-all: true
  disable:
    - gomnd
    - execinquery
    - exhaustruct
    - varnamelen
    - depguard
    - gci
    - gofumpt
