linters-settings:
  lll:
    line-length: 170
  goconst:
    ignore-tests: true
  revive:
    rules:
      - name: dot-imports
        disabled: true

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - wrapcheck
linters:
  enable-all: true
  disable:
    - gomnd
    - execinquery
    - exhaustruct
    - varnamelen
    - depguard
    - gci
    - gofumpt
    - tagalign
    - err113
    - nilnil
