apiVersion: kustomize.lburgazzoli.github.io/v1alpha1
kind: JQTransform
metadata:
  name: jq-transformer
  annotations:
    config.kubernetes.io/function: |
      container:
        image: quay.io/lburgazzoli/kustomize-plugin-jq:latest
spec:
  replacements:
    - sources:
        - selector:
            group: components.lburgazzoli.github.io
            version: v1alpha1
            kind: Configuration
            name: 'foo-config'
            predicate: '.spec.configuration.resources.type == "fixed"'
          name: '$fc'
        - selector:
            version: v1
            kind: ConfigMap
            name: 'foo-cm'
          name: '$fcm'
      targets:
        - selector:
            group: apps
            version: v1
            kind: Deployment
            name: 'foo-deployment'
          expressions:
            - '(.spec.template.spec.containers[] | select(.name == "manager")).resources.limits |= $fc.spec.configuration.resources.fixed.resources.limits'
            - '.spec.template.spec.containers[0].resources.requests = $fc.spec.configuration.resources.fixed.resources.requests'
            - '.spec.template.spec.containers[0].image = $fcm.data.image'
            - '.spec.replicas = $fc.spec.configuration.resources.fixed.replicas'
