apiVersion: kustomize.lburgazzoli.github.io/v1alpha1
kind: JQTransform
metadata:
  name: jq-transformer
  annotations:
    config.kubernetes.io/function: |
      container:
        image: quay.io/lburgazzoli/kustomize-plugin-jq:latest
spec:
  replacements:
    - sources:
        - selector:
            group: components.lburgazzoli.github.io
            version: v1alpha1
            kind: Configuration
            name: 'foo-config'
          name: '$fc'
        - selector:
            version: v1
            kind: ConfigMap
            name: 'foo-cm'
          name: '$fcm'
      targets:
        - selector:
            group: apps
            version: v1
            kind: Deployment
            name: 'foo-deployment'
          expressions:
            - |
              if ( $fc.spec.configuration.resources.type == "fixed" )
              then
                . | (.spec.template.spec.containers[] | select(.name == "manager")).resources |= $fc.spec.configuration.resources.fixed.resources
                  | .spec.replicas = $fc.spec.configuration.resources.fixed.replicas
              end
            - |
              if ( $fc.spec.configuration.resources.type == "fixed" )
              then
                .spec.replicas = $fc.spec.configuration.resources.fixed.replicas
              end
            - '.spec.template.spec.containers[0].image = $fcm.data.image'
            - '.spec.replicas = $fc.spec.configuration.resources.fixed.replicas'