---
apiVersion: v1
kind: ConfigMap
metadata:
  name: foo-cm
data:
  image: "quay.io/lburgazzoli/component:v1.1"
---
apiVersion: components.lburgazzoli.github.io/v1alpha1
kind: Configuration
metadata:
  name: foo-config
spec:
  configuration:
    resources:
      type: fixed
      fixed:
        replicas: 1
        resources:
          limits:
            cpu: 123m
            memory: 456Mi
          requests:
            cpu: 321m
            memory: 654Mi
