apiVersion: config.kubernetes.io/v1
kind: ResourceList
functionConfig:
  apiVersion: kustomize.lburgazzoli.github.io/v1alpha1
  kind: JQTransform
  metadata:
    name: jq-transformer
    annotations:
      config.kubernetes.io/function: |
        container:
          image: quay.io/lburgazzoli/kustomize-plugin-jq:latest
  spec:
    replacements:
      - source:
          group: components.lburgazzoli.github.io
          version: v1alpha1
          kind: Configuration
          name: 'foo-config'
          expression: '.spec.configuration.resources.type == "fixed"'
        targets:
          - group: apps
            version: v1
            kind: Deployment
            name: 'foo-deployment'
            expressions:
              - '(.spec.template.spec.containers[] | select(.name == "manager")).resources.limits |= $foo_config.spec.configuration.resources.fixed.resources.limits'
              - '.spec.template.spec.containers[0].resources.requests = $foo_config.spec.configuration.resources.fixed.resources.requests'
              - '.spec.replicas = $foo_config.spec.configuration.resources.fixed.replicas'
  items:
  - apiVersion: components.lburgazzoli.github.io/v1alpha1
    kind: Configuration
    metadata:
      name: foo-config
    spec:
      configuration:
        resources:
          type: fixed
          fixed:
            replicas: 1
            resources:
              limits:
                cpu: 123m
                memory: 456Mi
              requests:
                cpu: 321m
                memory: 654Mi
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: foo-deployment
    spec:
      replicas: 3
      selector:
        matchLabels:
          control-plane: foo-component
      template:
        metadata:
          labels:
            app: odh-component
        spec:
          containers:
            - name: manager
              image: quay.io/lburgazzoli/component:latest
              resources:
                limits:
                  cpu: 500m
                  memory: 2Gi
                requests:
                  cpu: 10m
                  memory: 64Mi